ChartValues:
  replicaCount: ${ReplicaCount}
  service:
    port: 8080
    type: LoadBalancer
HelmChartPath: Chart
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: Alicloud-ComputeNest/spring-boot-chart
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: Number
  AllowedPattern: ''
  Label: ReplicaCount
  MinValue: 1
  ConstraintDescription: ''
  MaxValue: 10
  Default: '1'
  Name: ReplicaCount
OutputType: HelmNotes
Owner: Alicloud-ComputeNest
Branch: main
Platform: github
