Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: 'Template'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
  DeployMetadata:
    SupplierDeployMetadata:
      RoleName: ComputeNestDeploy
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: Template
          Url: 'ros_templates/template.yaml'
          PredefinedParameters: []
          HiddenParameterKeys:
            - ClusterId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - ClusterId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    ClusterId: c8a3b437d0fc54faaabdb7f96e7ebe721
      HelmChartArtifactRelation:
        '{{ computenest::helmchart::spring-boot-chart }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: helm chart deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: HelmChart
    ArtifactName: spring-boot-chart-helm-chart
    ArtifactProperty:
      RepoName: ${HelmChartBuilder.HelmChart_1.RepoName}
      Tag: ${HelmChartBuilder.HelmChart_1.Tag}
HelmChartBuilder:
  HelmChart_1:
    HelmChartPath: 'resources/artifact_resources/helm_chart/spring-boot-chart-0.1.0.tgz'
    RepoName: spring-boot-chart
    Tag: 0.1.0